image: node:lts

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run test:unit
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - echo "@acrolinx:registry=https://gitlab.com/api/v4/packages/npm/" > .npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - echo "//gitlab.com/api/v4/projects/69851120/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  only:
    - main
    - tags
  when: manual
