image: node:lts

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run test:unit
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    # Configure npm registry
    - |
      echo "@acrolinx:registry=https://gitlab.com/api/v4/packages/npm/" > .npmrc
      echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
      echo "//gitlab.com/api/v4/projects/69851120/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    
    # Increment patch version
    - npm version patch --no-git-tag-version
    
    # Get the new version
    - NEW_VERSION=$(node -p "require('./package.json').version")

    # Publish package
    - npm publish
    
    # Create git tag
    - |
      git config --global user.email "${SERVICE_USER_EMAIL}"
      git config --global user.name "${SERVICE_USER_NAME}"
      git remote set-url origin "https://${SERVICE_USER_NAME}:${SERVICE_USER_GIT_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git"
      git add package.json package-lock.json
      git commit -m "chore: bump version to ${NEW_VERSION}"
      git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
      git push origin HEAD:${CI_COMMIT_REF_NAME}
      git push origin "v${NEW_VERSION}"
  only:
    - main
  when: manual
