name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          TEST_PLATFORM_URL: ${{ secrets.TEST_PLATFORM_URL }}
        run: npm run test:integration

      - name: Build
        run: npm run build
