name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@acrolinx'

      - name: Build And Test
        run: |
          npm ci
          npm run lint
          npm run test:unit
          npm run build

      - name: Publish to GitHub Package Registry
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
          scope: '@acrolinx'

      - name: Push Tag
        uses: anothrNick/github-tag-action@v1
        env:
          CUSTOM_TAG: v${{ steps.publish.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
