name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@acrolinx'

      - name: Build And Test
        run: |
          npm ci
          npm run lint
          npm run test:unit
          npm run build

      - name: Update version
        id: version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

      - name: Publish to GitHub Package Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
          npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Tag
        uses: anothrNick/github-tag-action@v1
        env:
          CUSTOM_TAG: v${{ steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 